static const char* const basic_class_names[] = {
  "Object",
  "Proc",
  "False",
  "True",
  "Nil",
  "Array",
  "Fixnum",
  "String",
  "Symbol",
  "Range",
  "Arduino",
};

static const char* const static_procs[] = {
  //class name => sym_id, Ruby method name => sym_id, C func name,
  "Object","puts","c_puts",
  "Object","!","c_object_not",
  "Object","!=","c_object_neq",
  "Object","<=>","c_object_compare",
  "Object","to_s","c_object_to_s",
  //"Object","new","c_object_new",
  "Object","class","c_object_class",
  "Object","attr_reader","c_object_attr_reader",
  "Object","attr_accessor","c_object_attr_accessor",
  "Fixnum","[]","c_fixnum_bitref",
  "Fixnum","-@","c_fixnum_negative",
  "Fixnum","**","c_fixnum_power",
  "Fixnum","%","c_fixnum_mod",
  "Fixnum","&","c_fixnum_and",
  "Fixnum","|","c_fixnum_or",
  "Fixnum","^","c_fixnum_xor",
  "Fixnum","~","c_fixnum_not",
  "Fixnum","<<","c_fixnum_lshift",
  "Fixnum",">>","c_fixnum_rshift",
  "Fixnum","abs","c_fixnum_abs",
  "Fixnum","times","c_fixnum_times",
  "Fixnum","chr","c_fixnum_chr",
  "Fixnum","to_i","c_ineffect",
  "Fixnum","to_s","c_fixnum_to_s",
  "String","+","c_string_add",
  "String","===","c_string_eql",
  "String","size","c_string_size",
  "Arduino","pin_mode","class_arduino_pin_mode",
  "Arduino","digital_write","class_arduino_digital_write",
  "Arduino","digital_read","class_arduino_digital_read",
  "","","",//don't delete this line
};

