static char* static_symbols[] = {
//Class
   "Object","",
   "String","",
   "Nil","",
   "Proc","",
   "False","",
   "True","",
   "Fixnum","",
   "Symbol","",
   "Array","",
   "Range","",
   "Hash","",
   "Arduino","",
 //method
   "+","ESC_01",
   "===","ESC_02",
   "<<","ESC_03",
   "[]","ESC_04",
   "[]=","ESC_05",
   "()","ESC_LAMBDA",
   "-","ESC_06",
   ">>","ESC_07",
};
